### ISSUE TITLE
Projektvereinbarung

### ISSUE THREAD

**Issue by Christian-Seiler** [Matchbook-One/GameCenter#27]
Due: 2022-12-19

- [ ] Christian-Seiler/Matchbook-One-GameCenter#26 
- [ ] Christian-Seiler/Matchbook-One-GameCenter#25 
- [ ] Christian-Seiler/Matchbook-One-GameCenter#24 
- [ ] Christian-Seiler/Matchbook-One-GameCenter#30 
- [ ] Christian-Seiler/Matchbook-One-GameCenter#31
- [x] ~#9~
